### ISSUE TITLE
Space after last thumb

### ISSUE THREAD

**Issue by petosiso** [zillow/react-slider#213] opened 2021-02-27 15:37 UTC
Hi,

I am trying to implement react-slider with 6 marks. I can't place the last thumb at the end of the track -  I have always space after the last thumb (see the image). How can I solve this? 

![image](https://user-images.githubusercontent.com/64576633/109392026-26ae4d80-791a-11eb-9329-8e80b6ff7de8.png)

Thank you!

**Comment by Sheldonfrith** [comment] 2021-03-14 13:47
Having same issue. This is a duplicate of #210

**Comment by mat-sf** [comment] 2021-03-19 17:04
The problem here is that browser returns different values from `slider.getBoundingClientRect()`, after resizing the browser (doesn't matter is it resized vertically or horizontally), it should return proper values and work as expected.

A temporary workaround, not perfect, but working, could be programmatically invoke browser resize:
```
useEffect(() => {
  window.dispatchEvent(new Event('resize'));
}, []);
```

From a package perspective, probably updating;
```
this.resize()
```
to 
```
setTimeout(() => this.resize());
```
in line 374 in `componentDidMount` function should fix it in the package, but that would need a bit more tests.

**Comment by stonebk** [comment] 2021-05-18 21:54
Hi @petosiso, can you please add a codesandbox that reproduces your issue? Without seeing your code, it's extremely difficult to debug.

You can create a sandbox by clicking below. Once you add that, we can reopen the issue.

[![Edit zillow/react-slider](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zillowreact-slider-l3vuc?fontsize=14&hidenavigation=1&theme=dark)

**Closed as completed by stonebk** 2021-05-18 21:54 UTC
