### ISSUE TITLE
Issue with getBoundingClientRect() being called on undefined component

### ISSUE THREAD

**Issue by clayne11** [zillow/react-slider#63] opened 2015-11-27 06:03 UTC
[This PR](https://github.com/mpowaga/react-slider/pull/38) brought in a setTimeout before calling for getBoundingClientRect(). This can cause an issue in some situations where the component is unmounted before this call is made thus throwing an exception.

**Comment by blanchma** [comment] 2015-12-10 17:54
Same problem here: Uncaught TypeError: slider.getBoundingClientRect is not a function(anonymous function) @ react-slider.js?b78f:280

**Comment by iest** [comment] 2016-01-05 14:25
I'm getting the same issue.

**Comment by istrel** [comment] 2016-01-20 15:29
This issue is caused by updating component and therefore calling extra `this._handleResize`. After that `this.resizeTimeout` value rewritten with new timeout handle although old timeout is not cleared. So after unmounting the old `resizeTimeout` is still going to happen. When it happens it faces empty refs and therefore throws the error

**Comment by mpowaga** [comment] 2018-03-01 19:27
Closing this issue because #67 has been merged.

**Closed as completed by mpowaga** 2018-03-01 19:27 UTC
Labels: bug
